spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/loan_tracker
    username: tracker
    password: Mactaba0925

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_qouted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  web:
    error:
      path: /user/error
      whitelabel:
        enabled: false
  mvc:
    async:
      request-timeout: 3600000
server:
  port: 8080
